#+TITLE: Readme

* Преамбула
Я умышленное не выкладываю в открытый доступ задание и использую репозиторий с обфуцированным названием. Могу удалить этот код после просмостра, чтобы не светить тестовое.

* Краткое описание
Краткое описание того, что получилось.

- Клиент-серверное приложение на TCP.
- Фреймовый протокол поверх TCP. Можно было разработать разные протоколы для игры и для апи-сервера, но в целях простоты и экономии времени проект реализует единный протокол.
- Все реализовано с использованием экосистемы Tokio (tokio-streams, codec, frame)
- В основном все структуры данных и подходы выбирались исходя из приоритетов: Скорость реализации, Производительность. В первую очередь выполнялись функциональные требования, во вторую учитывалась производительность.
- Приложение не доработано до боевого состояния. Например список всех пользователей хранится в памяти и если приложение будет работать бесконечно долго, то оно рано или поздно упадет по OOM
- Местами имеется избыточное копирование, для основных структур данных можно рассмотреть альтернативные варианты. Например использовать dashmap, где-то можно запараллелить обработку. Но это потребует каких-то бенчмарков и замеров, а соответственно времени.
- Весь код снабжен подробными комментариями

Приятного просмотра!
